# Generated by Django 3.1 on 2024-03-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_auto_20240313_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='fotos/productos')),
                ('disponibilidad', models.IntegerField()),
                ('esta_disponible', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
