# Generated by Django 3.1 on 2024-03-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_variation'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulocarrito',
            name='variations',
            field=models.ManyToManyField(blank=True, to='tienda.Variation'),
        ),
    ]
